apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: pfs-pipeline
spec:
  params:
    - name: source-repo
      type: string
      description: Source repository name
      default: https://github.com/account-name/repo-name
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/account-name/repo-name
  workspaces:
    - name: pfs-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: "$(params.source-repo)"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pfs-shared-data
    - name: install-dependencies
      runAfter:
        - clone-repository
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pfs-shared-data
      params:
        - name: ARGS
          value:
            - clean-install
    - name: run-tests
      runAfter:
        - install-dependencies
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pfs-shared-data
      params:
        - name: ARGS
          value:
            - test
    - name: build-image
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pfs-shared-data
    - name: kustomize-build
      runAfter:
        - build-image
      params:
        - name: app-namespace
          value: manuel-hennig-pfs-day-5
        - name: app-name
          value: mh-planet-express
        - name: image-with-tag
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: kustomize-build
      workspaces:
        - name: source
          workspace: pfs-shared-data
    - name: test-deploy
      runAfter:
        - kustomize-build
      params:
        - name: app-namespace
          value: manuel-hennig-pfs-day-5
        - name: app-name
          value: mh-planet-express
      taskRef:
        kind: Task
        name: test-deploy
      workspaces:
        - name: source
          workspace: pfs-shared-data
    - name: gitops
      runAfter:
        - test-deploy
      taskRef:
        kind: Task
        name: gitops
      params:
        - name: app-name
          value: mh-planet-express
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pfs-shared-data
