apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
commonLabels:
  app: foo-ns
  app.kubernetes.io/instance: foo-namespace
  app.kubernetes.io/name: foo
images:
- name: quay.io/account-name/repo-name
  newName: quay.io/foo/bar
